name: Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: "Publish release"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3.0.2

      - name: Display structure of downloaded files
        run: ls -R